source 'https://rubygems.org'

gem 'rails', '4.2.0'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'turbolinks'
gem 'yajl-ruby'
gem 'pg', '0.18.1'
gem 'sidekiq'
gem 'octokit'
gem 'octicons-rails'
gem 'actionpack-action_caching'
gem 'newrelic_rpm'
gem 'redis'
gem 'unicorn'
gem 'httparty'
gem 'kaminari'

group :development, :test do
  gem 'byebug'  
  gem 'quiet_assets'
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem 'rspec-rails', '~> 3.0'
  gem 'factory_girl_rails'
  gem 'mocha'
end
